### ISSUE TITLE
Can't start SPDY server

### ISSUE THREAD

**Issue by ddossot** [normanmaurer/netty-in-action#14]
<pre>
$ mvn clean package exec:exec -Pchapter12-SpdyServer
[INFO] --- exec-maven-plugin:1.2.1:exec (default-cli) @ netty-in-action ---
Exception in thread "main" java.lang.NoSuchMethodError: sun.security.ssl.SSLContextImpl.getSuportedCipherSuiteList()Lsun/security/ssl/CipherSuiteList;
	at sun.security.ssl.SSLEngineImpl.getSupportedCipherSuites(SSLEngineImpl.java:1982)
	at io.netty.handler.ssl.JdkSslContext.<clinit>(JdkSslContext.java:101)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:359)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:311)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:217)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:131)
	at io.netty.handler.ssl.SslContext.newServerContext(SslContext.java:117)
	at com.manning.nettyinaction.chapter12.SpdyServer.main(SpdyServer.java:52)
</pre>

with:
<pre>
$ mvn -version
Apache Maven 3.2.3 (33f8c3e1027c3ddde99d3cdebad2656a31e8fdf4; 2014-08-11T13:58:10-07:00)
Maven home: /opt/java/apache-maven-3.2.3
Java version: 1.7.0_71, vendor: Oracle Corporation
Java home: /opt/java/jdk1.7.0_71/jre
Default locale: en_CA, platform encoding: UTF-8
OS name: "linux", version: "3.13.0-37-generic", arch: "amd64", family: "unix"
</pre>

**Comment by normanmaurer** [comment]
Could you try using java8?
