### ISSUE TITLE
chapter12  mvn -PSecureChatServer clean package exec:exec Exception in thread "main" java.security.cert.CertificateException: No provider succeeded to generate a self-signed certificate

### ISSUE THREAD

**Issue by youshulai123** [normanmaurer/netty-in-action#68]
mvn -PSecureChatServer clean package exec:exec
Exception in thread "main" java.security.cert.CertificateException: No provider succeeded to generate a self-signed certificate. See debug log for the root cause.
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:157)
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:110)
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:88)
        at io.netty.handler.ssl.util.SelfSignedCertificate.<init>(SelfSignedCertificate.java:79)
        at nia.chapter12.SecureChatServer.main(SecureChatServer.java:36)

**Comment by youshulai123** [comment]
顶顶顶

**Comment by He-Pin** [comment]
Which java version you are using @youshulai123
